"""The committed .pcapng files must match the script that writes them.

They are checked in so the suite does not depend on a generator running, and
regenerated by hand when the shape of the fixture changes. That combination
drifts silently unless something compares the two, which is what this does.
"""

from pathlib import Path

from tests.fixtures import make_fixtures


def test_tiny_matches_its_generator(tmp_path: Path) -> None:
    rebuilt = tmp_path / "tiny.pcapng"
    make_fixtures.write_pcapng(rebuilt, make_fixtures.build_tiny())
    assert rebuilt.read_bytes() == (make_fixtures.HERE / "tiny.pcapng").read_bytes(), (
        "tiny.pcapng is out of step with make_fixtures.py; "
        "run `uv run python -m tests.fixtures.make_fixtures`"
    )


def test_scan_matches_its_generator(tmp_path: Path) -> None:
    rebuilt = tmp_path / "scan.pcapng"
    make_fixtures.write_pcapng(rebuilt, make_fixtures.build_scan())
    assert rebuilt.read_bytes() == (make_fixtures.HERE / "scan.pcapng").read_bytes(), (
        "scan.pcapng is out of step with make_fixtures.py; "
        "run `uv run python -m tests.fixtures.make_fixtures`"
    )


def test_the_fixtures_stay_tiny() -> None:
    # Checked-in binaries earn their place by being small enough to not care
    # about. A megabyte fixture is a repository problem.
    for name in ("tiny.pcapng", "scan.pcapng"):
        assert (make_fixtures.HERE / name).stat().st_size < 64 * 1024, name


def test_timestamps_carry_real_nanoseconds() -> None:
    # The fixture exists partly to prove the nanosecond path. If its own
    # timestamps landed on microsecond boundaries it would prove nothing.
    assert make_fixtures.BASE_NS % 1000 != 0
